
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package cup.example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int TIMES = 6;
  public static final int FULLSTOP = 18;
  public static final int PLUS = 3;
  public static final int RPAREN = 8;
  public static final int INT = 15;
  public static final int EQUAL = 17;
  public static final int CHAR = 16;
  public static final int SEMI = 2;
  public static final int END = 23;
  public static final int IDENTIFIER = 19;
  public static final int LPAREN = 7;
  public static final int COLON = 11;
  public static final int PROGRAM = 21;
  public static final int BEGIN = 22;
  public static final int COMMA = 12;
  public static final int EOF = 0;
  public static final int NUMBER = 9;
  public static final int DIVIDE = 5;
  public static final int NEWLINE = 20;
  public static final int MINUS = 4;
  public static final int CONST = 13;
  public static final int error = 1;
  public static final int BOOL = 14;
  public static final int VAR = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "PLUS",
  "MINUS",
  "DIVIDE",
  "TIMES",
  "LPAREN",
  "RPAREN",
  "NUMBER",
  "VAR",
  "COLON",
  "COMMA",
  "CONST",
  "BOOL",
  "INT",
  "CHAR",
  "EQUAL",
  "FULLSTOP",
  "IDENTIFIER",
  "NEWLINE",
  "PROGRAM",
  "BEGIN",
  "END"
  };
}

