
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package cup.example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int DIVIDE = 5;
  public static final int CONST = 14;
  public static final int CHAR = 26;
  public static final int GE = 18;
  public static final int XOR = 23;
  public static final int LPAREN = 7;
  public static final int SEMI = 2;
  public static final int INT = 25;
  public static final int FOR = 34;
  public static final int MINUS = 4;
  public static final int RPAREN = 8;
  public static final int NOT = 20;
  public static final int AND = 21;
  public static final int LT = 16;
  public static final int OR = 22;
  public static final int BOOL = 24;
  public static final int COMMA = 13;
  public static final int BEGIN = 32;
  public static final int PLUS = 3;
  public static final int LE = 17;
  public static final int EOF = 0;
  public static final int EQUAL = 27;
  public static final int error = 1;
  public static final int PROGRAM = 31;
  public static final int NEWLINE = 30;
  public static final int NUMBER = 10;
  public static final int MOD = 9;
  public static final int TIMES = 6;
  public static final int COLON = 12;
  public static final int TO = 35;
  public static final int FULLSTOP = 28;
  public static final int END = 33;
  public static final int DIFF = 19;
  public static final int DOWNTO = 36;
  public static final int GT = 15;
  public static final int VAR = 11;
  public static final int DO = 37;
  public static final int IDENTIFIER = 29;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "PLUS",
  "MINUS",
  "DIVIDE",
  "TIMES",
  "LPAREN",
  "RPAREN",
  "MOD",
  "NUMBER",
  "VAR",
  "COLON",
  "COMMA",
  "CONST",
  "GT",
  "LT",
  "LE",
  "GE",
  "DIFF",
  "NOT",
  "AND",
  "OR",
  "XOR",
  "BOOL",
  "INT",
  "CHAR",
  "EQUAL",
  "FULLSTOP",
  "IDENTIFIER",
  "NEWLINE",
  "PROGRAM",
  "BEGIN",
  "END",
  "FOR",
  "TO",
  "DOWNTO",
  "DO"
  };
}

